flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- adjunctions-4.3
- aeson-0.11.2.0
- aeson-pretty-0.8.1
- attoparsec-0.13.0.2
- base-unicode-symbols-0.2.2.4
- bifunctors-5.4.1
- blaze-html-0.8.1.2
- blaze-markup-0.7.1.0
- bytestring-conversion-0.3.1
- case-insensitive-1.2.0.7
- comonad-5
- connection-0.2.6
- control-monad-omega-0.3.1
- datetime-0.3.1
- distributive-0.5.0.2
- dlist-0.8.0.1
- either-4.4.1.1
- exceptions-0.8.3
- expiring-cache-map-0.0.5.4
- free-4.12.4
- hspec-2.2.3
- hspec-core-2.2.3
- hspec-discover-2.2.3
- hspec-expectations-0.7.2
- http-api-data-0.2.4
- http-client-0.5.3.1
- http-client-tls-0.3.0
- http-date-0.0.6.1
- http-media-0.6.4
- http-types-0.9.1
- http2-1.6.1
- insert-ordered-containers-0.1.0.1
- iproute-1.7.0
- kan-extensions-5.0.1
- lackey-0.4.0
- lens-4.14
- lifted-base-0.2.3.8
- network-2.6.3.1
- opaleye-0.5.0.0
- postgresql-simple-0.5.2.1
- product-profunctors-0.7.1.0
- profunctors-5.2
- psqueues-0.2.2.2
- pwstore-fast-2.4.4
- quickcheck-io-0.1.3
- reflection-2.1.2
- resourcet-1.1.7.4
- scientific-0.3.4.9
- semigroupoids-5.1
- servant-0.8.1
- servant-blaze-0.7.1
- servant-client-0.8.1
- servant-docs-0.8.1
- servant-foreign-0.8
- servant-js-0.8
- servant-mock-0.8.1
- servant-server-0.8.1
- servant-swagger-1.1.1
- servant-swagger-ui-0.2.0.2.1.5
- setenv-0.1.1.3
- simple-sendfile-0.2.25
- socks-0.5.5
- streaming-commons-0.1.15.5
- swagger2-2.1.2.1
- syb-0.6
- tagged-0.8.5
- tls-1.3.8
- wai-3.2.1.1
- wai-app-static-3.1.5
- wai-cors-0.2.5
- wai-extra-3.0.16.1
- wai-logger-2.3.0
- wai-middleware-static-0.8.0
- warp-3.2.7
resolver: ghc-8.0.1
